spring:
  datasource:
    url: jdbc:mysql://119.3.184.113:3306/animationmaster?characterEncoding=utf-8
    username: root
    password: Zhiku_qr_123
    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#      location: /AnimationMasterData/upload
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 80
  tomcat:
      uri-encoding: UTF-8
  servlet:
      context-path: /
#logging:
#  level:
#    com.zhiku.*: debug

