spring:
  datasource:
    url: jdbc:mysql://cdb-nj2smsfc.bj.tencentcdb.com:10001/animationmaster?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: train_60321
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jackson:
    time-zone: GMT+8  #配置返回给前端时区（默认伦敦时区）加：spring.jackson.time-zone:GMT+8
#      location: /AnimationMasterData/upload
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8
  servlet:
      context-path: /
#logging:
#  level:
#    com.zhiku.*: debug

#配置变量

DLServerIP: 127.0.0.1
DLServerUserName: ubuntu
DLServerPassword: 123456
DLServerSecretKey: /home/ubuntu/miyao1.pem
ExecShellSingleDir: /home/ubuntu/CartoonGAN-Test-Pytorch-Torch/processSingleDir.sh
ExecShellSinglePic: /home/ubuntu/CartoonGAN-Test-Pytorch-Torch/processSinglePic.sh

#文件存储根目录
fileRoot: /home/ubuntu/web
#工具储存根目录
toolsRoot: /home/ubuntu/web/tools
#补帧工程目录,主执行文件patch_frame.py的父目录
pfRoot: /home/ubuntu/web/Super-SloMo-changing


##风格类型对应实际风格决定参数值
#typle2Value:
#  audio: "{1: 0,2: 7,3: -7}" #风格id对应音调变化量
#  image: "{1: 'Shinkai',2: 'Hosoda',3: 'Paprika',4: 'Hayao'}"



