spring:
  datasource:
    url: jdbc:mysql://192.168.0.242:3306/animationmaster?characterEncoding=utf-8
    username: root
    password: Zhiku_qr_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /AnimationMasterData/upload
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:com/example/demo/mapper/*.xml
server:
  port: 8080
#logging:
#  level:
#    com.zhiku.*: debug