spring:
  datasource:
    url: jdbc:mysql://119.3.184.113:3306/animationmaster?characterEncoding=utf-8
    username: root
    password: Zhiku_qr_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#      location: /AnimationMasterData/upload
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 9999
  tomcat:
      uri-encoding: UTF-8
  servlet:
      context-path: /
#logging:
#  level:
#    com.zhiku.*: debug

#配置变量

DLServerIP: 54.234.238.204
DLServerUserName: ubuntu
DLServerPassword: 123456
DLServerSecretKey: /home/ubuntu/miyao1.pem
ExecShell: /home/ubuntu/CartoonGAN-Test-Pytorch-Torch/test.sh
ExecShelltransferEnv: /home/ubuntu/CartoonGAN-Test-Pytorch-Torch/transferEnv.sh
ExecShelltransferSinglePic: /home/ubuntu/CartoonGAN-Test-Pytorch-Torch/transferSinglePic.sh
#风格类型对应实际风格决定参数值
typle2Value:
  audio: "{1: 0,2: 7,3: -7}" #风格id对应音调变化量
  image: "{1: 'Shinkai',2: 'Hosoda',3: 'Paprika',4: 'Hayao'}"

